### ISSUE TITLE
feat: login return specific error

### ISSUE THREAD

**Issue by tienthegainz** [vinhyenvodoi98/workflow_management_php_laravel#17]
**Make login return json for specific error**
`
{
 "success" => "false",
 "msg" => "Email not found"
}
`
`
{
"success" => "false",
 "msg" => "Password is wrong"
}
`

**Comment by vinhyenvodoi98** [comment]
@tienthegainz 
we need  return json for specific success too
```js
"success" : "true",
"msg" : "enjoy mother f",
"token" : "asdasfdsfd"
```
