### ISSUE TITLE
feat : high priority work API 

### ISSUE THREAD

**Issue by vinhyenvodoi98** [vinhyenvodoi98/workflow_management_php_laravel#42]
return object array priority work

**Comment by DrNguyen2525** [comment]
works.priority = 'high'

**Comment by tienthegainz** [comment]
![Screenshot from 2019-11-21 16-48-18](https://user-images.githubusercontent.com/34891363/69326753-e8d66a00-0c7e-11ea-9244-c9f25e0ed0ea.png)
