### ISSUE TITLE
feat : work remind API 

### ISSUE THREAD

**Issue by vinhyenvodoi98** [vinhyenvodoi98/workflow_management_php_laravel#43]
return work remind

**Comment by DrNguyen2525** [comment]
user_work.role = 'Accountable'

**Comment by tienthegainz** [comment]
![Screenshot from 2019-11-21 16-48-18](https://user-images.githubusercontent.com/34891363/69327112-8df14280-0c7f-11ea-9dc6-51abd4a3896e.png)
