### ISSUE TITLE
feat : work schedule

### ISSUE THREAD

**Issue by vinhyenvodoi98** [vinhyenvodoi98/workflow_management_php_laravel#44]
return work schedule

**Comment by tienthegainz** [comment]
![Screenshot from 2019-11-21 16-53-38](https://user-images.githubusercontent.com/34891363/69327182-a8c3b700-0c7f-11ea-9881-19801054eeb9.png)

**Comment by DrNguyen2525** [comment]
works.created_at, updated_at, status
