### ISSUE TITLE
feat : work statistic

### ISSUE THREAD

**Issue by vinhyenvodoi98** [vinhyenvodoi98/workflow_management_php_laravel#45]
return number of work :

- Not started
- In progress
- Approval pending
- Done

and all

**Comment by tienthegainz** [comment]
![Screenshot from 2019-11-21 16-48-18](https://user-images.githubusercontent.com/34891363/69327066-7fa32680-0c7f-11ea-8949-e30f1d73e687.png)

**Comment by DrNguyen2525** [comment]
works.status
