### ISSUE TITLE
Có hình ảnh giới thiệu không thím?

### ISSUE THREAD

**Issue by vfic** [vinhyenvodoi98/workflow_management_php_laravel#71]
Cho mình xin 500đ ảnh nhé. Thanks.

**Comment by vinhyenvodoi98** [comment]
@vfic 
Chào bạn project bên mình vẫn đang trong giai đoạn phát triển đây là một  số hình ảnh giới thiệu về project 
![image](https://user-images.githubusercontent.com/33363513/70883465-ac8bf480-2005-11ea-91d4-e64763f2b140.png)
![image](https://user-images.githubusercontent.com/33363513/70883535-de04c000-2005-11ea-849a-4fbac65e0040.png)

Ngoài **light** mode thì bên mình còn hỗ trợ **dark** mode 
![image](https://user-images.githubusercontent.com/33363513/70883614-1d331100-2006-11ea-8d27-c97b7c2018ab.png)
![image](https://user-images.githubusercontent.com/33363513/70883692-697e5100-2006-11ea-9e00-0be9608d127d.png)

Ngoài ra nếu ko thích navbar thì có thể chọn chế độ sidebar 
![image](https://user-images.githubusercontent.com/33363513/70883666-4eabdc80-2006-11ea-9451-d8d3e367da0f.png)

**Comment by vinhyenvodoi98** [comment]
nếu có bất cứ vấn đề về việc cài đặt và chạy thì bạn có thể cmt bên dưới mình tạm đóng issue này
